apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: argocd
spec:
  project: default
  source:
    # helm subchart deployment pattern
    repoURL: https://github.com/MRostanski/cluster-argo-setup.git
    targetRevision: HEAD
    path: tools/kube-state-metrics
    # directory:
    #   recurse: true
    helm:
      valueFiles:
        - ./values/prod.yaml
      # value file parameters override
      parameters:
        - name: kube-state-metrics.replicas
          value: "1"
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
